// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SACCOBlockChainSystem.Data;

#nullable disable

namespace SACCOBlockChainSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260211113244_CreateGLSETUPTable")]
    partial class CreateGLSETUPTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SACCOBlockChainSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<string>("BlockHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MerkleRoot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Nonce")
                        .HasColumnType("int");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("BlockId");

                    b.HasIndex("BlockHash")
                        .IsUnique();

                    b.HasIndex("PreviousHash");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.BlockchainTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MemberNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OffChainReferenceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("BlockHash");

                    b.HasIndex("MemberNo");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("TransactionType");

                    b.ToTable("BlockchainTransactions");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Acs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Othername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Unsubscribe")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cigcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contactperson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoEmployees")
                        .HasColumnType("int");

                    b.Property<int?>("NoYears")
                        .HasColumnType("int");

                    b.Property<bool>("Project")
                        .HasColumnType("bit");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unitcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Contrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlockchainTxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CashBookdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContrDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContraAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DepositedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dregard")
                        .HasColumnType("int");

                    b.Property<string>("Locked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MemberNoNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("MrCleared")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mrno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Offs")
                        .HasColumnType("int");

                    b.Property<bool?>("Offset")
                        .HasColumnType("bit");

                    b.Property<string>("Posted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Run")
                        .HasColumnType("bigint");

                    b.Property<int?>("Run2")
                        .HasColumnType("int");

                    b.Property<string>("Schemecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShareBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SharesAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sharescode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StaffNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransferDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainTxId");

                    b.HasIndex("MemberNo");

                    b.HasIndex("MemberNoNavigationId");

                    b.HasIndex("Sharescode");

                    b.ToTable("Contribs");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.ContribShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlockchainTxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContrDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DepositedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DepositsAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Donor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalId")
                        .HasColumnType("int");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("PassBookAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RegFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShareCapitalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sharescode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainTxId");

                    b.HasIndex("MemberNo");

                    b.HasIndex("Sharescode");

                    b.ToTable("ContribShares");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.CoopTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckoutRequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantRequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultCode")
                        .HasColumnType("int");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShortCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CoopTransactions");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.GeneralLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AccBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Chequeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Credits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Debits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Glname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Transdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GeneralLedgers");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Gltransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cash")
                        .HasColumnType("int");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrAccNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocPosted")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrAccNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Dregard")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Recon")
                        .HasColumnType("bit");

                    b.Property<int>("ReconId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransDescript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gltransactions");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Aamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AddSecurity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApplicDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppraisalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AppraisalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BlockchainTxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Bridging")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cshares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisbursementBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DisbursementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndorsementBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndorsementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gperiod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Grosspay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Guaranteed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuarantorBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuarantorDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InsCalcType")
                        .HasColumnType("int");

                    b.Property<decimal?>("InsPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Insurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JobGrp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LoanAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("LoanTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("Loancount")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("MaxLoanamt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Phcf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Posted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PremiumPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreparedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Refinancing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepayMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepayPeriod")
                        .HasColumnType("int");

                    b.Property<decimal?>("Repayrate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Rescheduledate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Run")
                        .HasColumnType("int");

                    b.Property<int?>("Run2")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Sharecapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sourceofrepayment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupMemberNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupSigned")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitMemberNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WitSigned")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainTxId");

                    b.HasIndex("LoanNo")
                        .IsUnique();

                    b.HasIndex("LoanTypeId");

                    b.HasIndex("MemberNo");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loanbal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AutoCalc")
                        .HasColumnType("bit");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CategoryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cleared")
                        .HasColumnType("bit");

                    b.Property<string>("Companycode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Defaulter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Duedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gperiod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Installments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestAccrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntrAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntrCharged")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntrOwed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntrOwed2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Nextduedate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Penalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Processdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Receiptno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepayMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RepayMode")
                        .HasColumnType("smallint");

                    b.Property<int>("RepayPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("RepayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RepayRate2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Run")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoanNo");

                    b.ToTable("Loanbals");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loanguar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Collateral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoanId")
                        .HasColumnType("int");

                    b.Property<string>("LoanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tguaranto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Transdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Transfered")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("Loanguars");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loantype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccruedAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Bankloan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Bridgefees")
                        .HasColumnType("float");

                    b.Property<bool>("Bridging")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLoanno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EarningRation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GracePeriod")
                        .HasColumnType("int");

                    b.Property<string>("Guarantor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insurance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntAccno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intrecovery")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFimg")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("LoanAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanOverpaymentAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanType1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxLoans")
                        .HasColumnType("int");

                    b.Property<short>("Mdtei")
                        .HasColumnType("smallint");

                    b.Property<short>("MinimumPaidForBridging")
                        .HasColumnType("smallint");

                    b.Property<short>("MinimumPaidForTopup")
                        .HasColumnType("smallint");

                    b.Property<string>("MobileCreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MobileCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MobileLoan")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Nssf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OtherDeduct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OverpaymentAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Penalty")
                        .HasColumnType("bit");

                    b.Property<string>("PenaltyAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Periodrepaid")
                        .HasColumnType("int");

                    b.Property<string>("Ppacc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PremiumAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PremiumContraAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<decimal?>("Processingfee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceivableAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepayPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Repaymethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SelfGuarantee")
                        .HasColumnType("bit");

                    b.Property<bool?>("UseintRange")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueChain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaitingPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Loantypes");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accepted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Accno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApplicDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AsAtDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockchainTxId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BlockchainTxId");

                    b.Property<string>("Bname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cigcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Dormant")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entrance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFilled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idno")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("InitShares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InitsharesTransfered")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterestBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LoanBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MemberDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MembershipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Memberwitrawaldate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MonthlyContr")
                        .HasColumnType("float");

                    b.Property<bool?>("Mstatus")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresentAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfileString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RegFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Run")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShareCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Signed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Station")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Transferdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Withdrawn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainTxId");

                    b.HasIndex("Idno");

                    b.HasIndex("MemberNo")
                        .IsUnique();

                    b.HasIndex("PhoneNo");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.MemberNumberCounter", b =>
                {
                    b.Property<string>("CompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyCode");

                    b.ToTable("MemberNumberCounters");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Repay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Accrued")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlockchainTxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrgLoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BridgeInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Cash")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CashBookDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chequeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dregard")
                        .HasColumnType("int");

                    b.Property<decimal?>("IntBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Interest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InterestAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Interestaccrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntrAccrued")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntrCharged")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IntrOwed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LoanBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Loancode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("MemberNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mrcleared")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mrno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Nextduedate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Offs")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentNo")
                        .HasColumnType("int");

                    b.Property<decimal?>("Penalty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("Posted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Principal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RepayId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RepayRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Run")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Statementdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainTxId");

                    b.HasIndex("LoanNo");

                    b.HasIndex("MemberNo");

                    b.ToTable("Repays");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Share", b =>
                {
                    b.Property<string>("MemberNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sharescode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Initshares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastDivDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Loanbal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Statementshares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalShares")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberNo", "Sharescode");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Sharetype", b =>
                {
                    b.Property<string>("SharesCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Accno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ElseRatio")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Guarantor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Interest")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsMainShares")
                        .HasColumnType("bit");

                    b.Property<int?>("Issharecapital")
                        .HasColumnType("int");

                    b.Property<float?>("LoanToShareRatio")
                        .HasColumnType("real");

                    b.Property<bool>("Loanquaranto")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowerLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PlacePeriod")
                        .HasColumnType("int");

                    b.Property<string>("Ppacc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Shareboost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharesAcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsedToGuarantee")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedToOffset")
                        .HasColumnType("bit");

                    b.Property<bool>("Withdrawable")
                        .HasColumnType("bit");

                    b.HasKey("SharesCode");

                    b.ToTable("Sharetypes");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlockchainTxId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Channel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.TransactionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckoutRequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantRequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultCode")
                        .HasColumnType("int");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShortCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TransactionDetails");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Transactions2", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AuditTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BlockchainTxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Companycode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContributionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepositedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RunE")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainTxId");

                    b.HasIndex("MemberNo");

                    b.ToTable("Transactions2");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.UserAccounts1", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignGl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Authorize")
                        .HasColumnType("bit");

                    b.Property<string>("Branchcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cigcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Count")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Euser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expirydate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Levels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassExpire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCounty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Superuser")
                        .HasColumnType("bigint");

                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLoginId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("VendorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserAccounts1");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrivateKeyEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.WicciClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Othername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subscription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Unsubscribe")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WicciClients");
                });

            modelBuilder.Entity("YourProject.Models.GlSetup", b =>
                {
                    b.Property<long>("GlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GlId"));

                    b.Property<string>("AccCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Actuals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuditOrg")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Bal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BalanceSheet")
                        .HasColumnType("int");

                    b.Property<decimal?>("Budgetted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Curr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("CurrCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EoyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EoyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GlAccMainGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GlOrder")
                        .HasColumnType("int");

                    b.Property<string>("GlType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Glaccgroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Glaccname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Glaccstatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Glacctype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Glcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsREarning")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSubLedger")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspense")
                        .HasColumnType("bit");

                    b.Property<bool?>("Main")
                        .HasColumnType("bit");

                    b.Property<decimal>("NewGlOpeningBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NewGlOpeningBalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Normalbal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("OpeningBal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PrintOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrialBalance")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Used")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GlId");

                    b.ToTable("GLSETUP");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.BlockchainTransaction", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Block", "Block")
                        .WithMany("Transactions")
                        .HasForeignKey("BlockHash")
                        .HasPrincipalKey("BlockHash");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Contrib", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Member", "MemberNoNavigation")
                        .WithMany()
                        .HasForeignKey("MemberNoNavigationId");

                    b.HasOne("SACCOBlockChainSystem.Models.Sharetype", "SharescodeNavigation")
                        .WithMany("Contribs")
                        .HasForeignKey("Sharescode");

                    b.Navigation("MemberNoNavigation");

                    b.Navigation("SharescodeNavigation");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.ContribShare", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Sharetype", "SharescodeNavigation")
                        .WithMany("ContribShares")
                        .HasForeignKey("Sharescode");

                    b.Navigation("SharescodeNavigation");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loan", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Loantype", "LoanType")
                        .WithMany()
                        .HasForeignKey("LoanTypeId");

                    b.HasOne("SACCOBlockChainSystem.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberNo")
                        .HasPrincipalKey("MemberNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanType");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loanbal", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Loan", null)
                        .WithMany("Loanbals")
                        .HasForeignKey("LoanNo")
                        .HasPrincipalKey("LoanNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loanguar", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Loan", null)
                        .WithMany("LoanGuarantors")
                        .HasForeignKey("LoanId");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Repay", b =>
                {
                    b.HasOne("SACCOBlockChainSystem.Models.Loan", null)
                        .WithMany("Repays")
                        .HasForeignKey("LoanNo")
                        .HasPrincipalKey("LoanNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Block", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Loan", b =>
                {
                    b.Navigation("LoanGuarantors");

                    b.Navigation("Loanbals");

                    b.Navigation("Repays");
                });

            modelBuilder.Entity("SACCOBlockChainSystem.Models.Sharetype", b =>
                {
                    b.Navigation("ContribShares");

                    b.Navigation("Contribs");
                });
#pragma warning restore 612, 618
        }
    }
}
